== Command Line Interface and Resources

Now that you have created an application to work with, the list of key resource objects which have been created within the project can be listed using the:

`oc get all`

command. The output you will see from running this command will be similar to the following:

```
NAME                   READY   STATUS      RESTARTS   AGE
pod/greeter-1-c9mkw    1/1     Running     0          93m
pod/greeter-1-deploy   0/1     Completed   0          117m
pod/greeter-1-l6xmv    1/1     Running     0          92m

NAME                              DESIRED   CURRENT   READY   AGE
replicationcontroller/greeter-1   2         2         2       117m

NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/greeter   ClusterIP   172.30.33.137   <none>        8080/TCP   117m

NAME                                         REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfig.apps.openshift.io/greeter   1          2         2         config,image(greeter:latest)

NAME                                                      IMAGE REPOSITORY                                                                                                                  TAGS     UPDATED
imagestream.image.openshift.io/greeter                    default-route-openshift-image-registry.apps.cluster-sin-1975.sin-1975.openshiftworkshop.com/tutorial-1/greeter                    latest   2 hours ago
imagestream.image.openshift.io/knative-tutorial-greeter   default-route-openshift-image-registry.apps.cluster-sin-1975.sin-1975.openshiftworkshop.com/tutorial-1/knative-tutorial-greeter   latest   2 hours ago

NAME                               HOST/PORT                                                                 PATH   SERVICES   PORT       TERMINATION   WILDCARD
route.route.openshift.io/greeter   greeter-tutorial-1.apps.cluster-sin-1975.sin-1975.openshiftworkshop.com          greeter    8080-tcp                 None
```

You can restrict the output to just the names of the resources by running:

`oc get all -o name`

In other words, supply the `-o name` option to change the output format.

```
pod/greeter-1-c9mkw
pod/greeter-1-deploy
pod/greeter-1-l6xmv
replicationcontroller/greeter-1
service/greeter
deploymentconfig.apps.openshift.io/greeter
imagestream.image.openshift.io/greeter
imagestream.image.openshift.io/knative-tutorial-greeter
route.route.openshift.io/greeter
```

The `oc get` command is the most basic command that exists in OpenShift for querying resource objects. You will use it a lot, so you should become familiar with it, as well as how to update resource objects.

In addition to being able to use the special name ``all`` to query information about the key resource object types, you can also list specific object types by name. You can for example get a list of the routes created when applications have been exposed by running:

`oc get routes`

For the application you have deployed, you should see something like:

```
NAME      HOST/PORT                                                                 PATH   SERVICES   PORT       TERMINATION   WILDCARD
greeter   greeter-tutorial-1.apps.cluster-sin-1975.sin-1975.openshiftworkshop.com          greeter    8080-tcp                 None
```

You can get a list of all the different resource object types you can query by running

`oc get`

without any specific object type listed. This will output

```
You must specify the type of resource to get. Valid resource types include:

    * all
    * buildconfigs (aka 'bc')
    * builds
    ...
    * users
    * storageclasses
    * thirdpartyresources
    error: Required resource not specified.
Use "oc explain <resource>" for a detailed description of that resource (e.g. oc explain pods).
See 'oc get -h' for help and examples.
```

In addition to being able to be queried using their full name, many resource object types can be queried using a shorter alias. You can therefore use `bc instead of `buildconfigs`.

In all cases where the `type` of a resource object is listed as a plural, you can also use the `type` in its singular form. You can therefore use `route instead of `routes`.

A high level description of the main resource object types, and other concepts, can be obtained by running the:

`oc api-resources`

command.

```
Concepts and Types

Kubernetes and OpenShift help developers and operators build, test, and deploy
applications in a containerized cloud environment. Applications may be composed
of all of the components below, although most developers will be concerned with
Services, Deployments, and Builds for delivering changes.

Concepts:

* Containers:
    A definition of how to run one or more processes inside of a portable Linux
    environment. Containers are started from an Image and are usually isolated
    from other containers on the same machine.

* Image:
    A layered Linux filesystem that contains application code, dependencies,
    and any supporting operating system libraries. An image is identified by
    a name that can be local to the current cluster or point to a remote Docker
    registry (a storage server for images).

* Pods [pod]:
    A set of one or more containers that are deployed onto a Node together and
    share a unique IP and Volumes (persistent storage). Pods also define the
    security and runtime policy for each container.

...
```
