= Source-to-Image (S2I)

In a previous section, you learned how to deploy an application from a pre-existing Docker-formatted image. Here you will learn how to deploy an application direct from source code hosted in a remote Git repository. This will be done using the https://github.com/redhat/source-to-image[Source-to-Image (S2I)] tool.

The documentation for S2I describes itself in the following way:

> Source-to-image (S2I) is a tool for building reproducible Docker images. S2I
produces ready-to-run images by injecting source code into a Docker image and
assembling a new Docker image which incorporates the builder image and built
source. The result is then ready to use with docker run. S2I supports
incremental builds which re-use previously downloaded dependencies, previously
built artifacts, etc.

OpenShift is S2I-enabled and can use S2I as one of its build mechanisms (in addition to building Docker images from Dockerfiles and "custom" builds).

A full discussion of S2I is beyond the scope of this lab. More information about S2I can be found in the https://docs.openshift.org/latest/creating_images/s2i.html[OpenShift S2I documentation] and the https://github.com/openshift/source-to-image[GitHub project repository for S2I].

The only key concept you need to remember about S2I is that it's magic.

== Exercise: Deploying the application code

The backend service that you will be deploying in this section is called `helloworld`. This is a nodejs application that will return simple **Hello**  via a REST service API. The source code repository for the application can be found on GitHub at:

* https://github.com/redhat-developer-demos/linux-container-world-apps under directory **nodejs**

To deploy the application you are going to use the following command

[source,bash,subs="+macros,attributes+"]
----
oc new-app nodeshift/centos7-s2i-nodejs:10.x~https://github.com/redhat-developer-demos/linux-container-world-apps \
 --context-dir=nodejs \
 --name=helloworld
----

It will take a bit of time for the application to build and deploy, you can watch the status via the command:

[source,bash,subs="+macros,attributes+"]
----
oc logs -f bc/helloworld
----

With service now deployed you need to expose the service to get the public url:

[source,bash,subs="+macros,attributes+"]
----
# To create the route
oc expose svc/helloworld
----

[source,bash,subs="+macros,attributes+"]
----
export URL="http://$(oc get route | grep helloworld | awk '{print $2}')"
echo pass:[$URL]
curl pass:["$URL"]
----